#! /bin/bash
#xrandr --output DP-2 --primary
#xrandr --output DP-1 --left-of HDMI-1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config single_monocle 		 true
bspc config gapless_monocle      true

bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 
bspc monitor VGA-1 -d 0

# Dracula theme
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
bspc desktop -f 1

# Autostart
picom &
shuf -e -n1 .w/* | xargs feh --bg-fill
numlockx on &
xset b 0 &
xsetroot -cursor_name left_ptr &
xinput set-prop 21 330 -0.30 &

# Geogebra 5 bug
~/.config/java_nonreparenting_wm_hack.sh

pgrep -x polybar > /dev/null || polybar &

bspc rule -a Chromium desktop=1
bspc rule -a Gimp desktop=8
bspc rule -a Evince desktop=7
bspc rule -a okular desktop=7
bspc rule -a Code desktop=9
